[package]
name = "scx_fifo"
version = "0.0.1"
authors = ["Andrea Righi <andrea.righi@canonical.com>", "Canonical"]
edition = "2021"
description = "A simple FIFO scheduler in Rust"
license = "GPL-2.0-only"

[dependencies]
anyhow = "1.0.65"
ctrlc = { version = "3.1", features = ["termination"] }
hex = "0.4.3"
libbpf-rs = "0.22.0"
libc = "0.2.137"
scx_utils = { path = "../../../rust/scx_utils", version = "0.6" }
scx_user = { path = "../../../rust/scx_user", version = "0.1" }

[build-dependencies]
scx_utils = { path = "../../../rust/scx_utils", version = "0.6" }

[features]
enable_backtrace = []
