[package]
name = "scx_user"
version = "0.1.0"
edition = "2021"
authors = ["Andrea Righi <andrea.righi@canonical.com>"]
license = "GPL-2.0-only"
repository = "https://github.com/sched-ext/scx"
description = "User-space utilities for sched_ext schedulers"

[dependencies]
anyhow = "1.0"
bitvec = { version = "1.0", features = ["serde"] }
# FIXME - We need to allow both 0.68 and 0.69 to accommodate fedora. See the
# comment in BpfBuilder::bindgen_bpf_intf() for details.
bindgen = ">=0.68, <0.70"
glob = "0.3"
hex = "0.4.3"
lazy_static = "1.4"
libbpf-cargo = "0.22"
libbpf-rs = "0.22.0"
libc = "0.2.137"
buddy-alloc = "0.5.1"
log = "0.4.17"
regex = "1.10"
sscanf = "0.4"
tar = "0.4"
version-compare = "0.1"

[build-dependencies]
bindgen = ">=0.68, <0.70"
tar = "0.4"
walkdir = "2.4"
